### ISSUE TITLE
In vs2022, When enable the ChASM Extension, my cpp source file's autocomplete dead.

### ISSUE THREAD

**Issue by epitaphial** [ethicalblue/ChASM-x86-x64-Assembly-Syntax-Highlighter#2]
As the title says.

**Comment by ethicalblue** [comment]
Thank you for bug report on ChASM extension, but I cannot reproduce this bug. I have opened .cpp file and after pressing CTRL+SPACE the autocomplete mechanism works good.

![msvcpp_code_completion](https://user-images.githubusercontent.com/82314652/208917867-0687b858-983d-43c0-89a0-98fbfc33d5fa.png)

**Comment by epitaphial** [comment]
Thanks for your reply, I just disble it and enable it, it works again!
