### ISSUE TITLE
Why all of words' color are blue...

### ISSUE THREAD

**Issue by JMC2002** [ethicalblue/ChASM-x86-x64-Assembly-Syntax-Highlighter#4]

**Comment by ethicalblue** [comment]
Thank you for using ChASM extension. I have added more colors to the extension, but there are still no color settings without changing C# code. I hope you enjoy default colors.

![colorz](https://github.com/ethicalblue/ChASM-x86-x64-Assembly-Syntax-Highlighter/assets/82314652/b7e0ed71-5b7c-47c8-8077-03a741404770)

**Comment by JMC2002** [comment]
Oh, that's fantastic! This color scheme is much easier on my eyes! Thank you very much! 

Additionally, I've noticed that it only supports ASCII characters, not Unicode. When I try to input Unicode characters like '测试', they end up displaying as small blocks.
